### ISSUE TITLE
App gets crash with module ver 1.0.0

### ISSUE THREAD

**Issue by sunilh29** [prashantsaini1/android-titanium-imagecropper#2]
I am building my app with sdk 6.3.0.GA. App is getting crashed on Redmi 4 device but its perfectly working on other devices. Please help me with this. 

I also got the logs from DDMS which are:

02-26 21:48:10.728: E/AndroidRuntime(19360): FATAL EXCEPTION: main
02-26 21:48:10.728: E/AndroidRuntime(19360): Process: com.example.app, PID: 19360
02-26 21:48:10.728: E/AndroidRuntime(19360): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_atexit" referenced by "/data/app/com.example.app-1/lib/arm/libin.prashant.imagecrop.so"...
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at java.lang.System.loadLibrary(System.java:1076)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:151)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:118)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:136)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at com.thebarstockexchange.tbse.TbseApplication.onCreate(TbseApplication.java:67)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4761)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at android.app.ActivityThread.access$1700(ActivityThread.java:153)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1436)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at android.os.Looper.loop(Looper.java:154)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at android.app.ActivityThread.main(ActivityThread.java:5523)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at java.lang.reflect.Method.invoke(Native Method)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
02-26 21:48:10.728: E/AndroidRuntime(19360): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
02-26 21:48:10.745: W/Conscrypt(5956): Could not set socket write timeout:
02-26 21:48:10.770: E/MQSEventManagerDelegate(19360): failed to get MQSService.

**Comment by prashantsaini1** [comment]
Can't test it on Ti 6.x now. I would advise you to use only latest version with Ti 7.x
