### ISSUE TITLE
Fixed cropping ratio?

### ISSUE THREAD

**Issue by hansemannn** [prashantsaini1/android-titanium-imagecropper#5]
Hey @prashantsaini1, great module!

One question: Does this this module support a fixed cropping ratio, so we can limit the final width and height but allow the user to change the image to match this rect? The native lib has `setMinCropResultSize` and `setMaxCropResultSize` for this, so we may need to implement that?

**Comment by prashantsaini1** [comment]
It will be there in new version very soon!
However, you can rely on aspect-ratios for now if you don't need the exact sizes but rather the ratio. You can then resize the cropped image to required sizes.
