### ISSUE TITLE
Title bar doesn't show up to allow me to complete the crop

### ISSUE THREAD

**Issue by mark22** [prashantsaini1/android-titanium-imagecropper#7]
So my app has no title bar in it, everything is custom.  When the cropper launches, the titlebar/action bar doesn't show up at all, so you cannot complete the cropping process.

So I tried using the option to give it a theme but that still doesn't work

**theme:'@style/Theme.AppCompat.Translucent',**  

but still nothing.   

I cannot enable the action bar on my app systemwide, as it will ruin my app.   Is there anyway to get the action bar just to show up for this module?

**Comment by prashantsaini1** [comment]
You have to provide the theme name without the **@style**  and this theme must have action bar enabled.  e.g.

Suppose you have the below theme in your theme-xml file.

```
<?xml version="1.0" encoding="utf-8"?>

<resources xmlns:android="http://schemas.android.com/apk/res/android">
    <style name="ActionBarCustomTheme" parent="@style/Theme.AppCompat.Light">
        <item name="colorPrimary">#00bbaa</item>
        <item name="colorPrimaryDark">#008855</item>
        <item name="colorAccent">@color/accent</item>
        <item name="colorControlHighlight">@color/ripple</item>
    </style>
</resources>

```

then this code will work for you:
```
require('in.prashant.imagecrop').crop({
    theme : 'ActionBarCustomTheme',		// Any action-bar enabled theme
    callback : function(e) {....}
);
```
